filters: &filters 1024
repeat: &repeat 3
dropout: &dropout 0.1
separable: &separable true
se: &se true
se_context_size: &se_context_size -1
kernel_size_factor: &kernel_size_factor 1.0

featurizer:
  feat_in: 80
  activation: relu
  conv_mask: true

  jasper:
    -   filters: *filters
        repeat: 1
        kernel: [3]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: false
        separable: *separable
        se: *se
        se_context_size: *se_context_size

    -   filters: *filters
        repeat:  *repeat
        kernel: [7]
        stride: [1]
        dilation: [1]
        dropout: *dropout
        residual: true
        separable: *separable
        se: *se
        se_context_size: *se_context_size

    -   filters: *filters
        repeat: *repeat
        kernel: [11]
        stride: [1]
        dilation: [1]
        dropout: *dropout
        residual: true
        separable: *separable
        se: *se
        se_context_size: *se_context_size

    -   filters: *filters
        repeat: *repeat
        kernel: [15]
        stride: [1]
        dilation: [1]
        dropout: *dropout
        residual: true
        separable: *separable
        se: *se
        se_context_size: *se_context_size

    -   filters: &enc_feat_out 3072
        repeat: 1
        kernel: [1]
        stride: [1]
        dilation: [1]
        dropout: 0.0
        residual: false
        separable: *separable
        se: *se
        se_context_size: *se_context_size
  decoder:
        feat_in: *enc_feat_out
        pool_mode: 'attention'
        emb_sizes: 192

classifier:
  feat_in: 192

discriminator:
  feat_in: 192