crop:
  # Mandatory for speaker recognition task
  do_augment: True
  p: 1.0
  params:
    min_dur: 0.75
    max_dur: 4

speed:
  do_augment: False
  p: 0.2
  params:
    sr: 16000
    resample_type: 'soxr_hq'
    min_speed_rate: 0.9
    max_speed_rate: 1.1
    num_rates: 5

codec:
  do_augment: False
  p: 0.001
  params: {}

impulse:
  do_augment: True
  p: 0.1
  params:
    manifest_path: [
      /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-rir-pointsource_noises-dev-nonzeros.json,
      /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-rir-pointsource_noises-test-nonzeros.json,
      /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-rir-pointsource_noises-train-nonzeros.json,
      /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-rir-real_rirs-dev-nonzeros.json,
      /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-rir-real_rirs-test-nonzeros.json,
      /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-rir-real_rirs-train-nonzeros.json,
      /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-rir-simulated_rirs-dev-nonzeros.json,
      /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-rir-simulated_rirs-test-nonzeros.json,
      /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-rir-simulated_rirs-train-nonzeros.json
    ]
    shift_impulse: False

rir:
  do_augment: True
  p: 0.1
  params:
    rir_manifest_path: [
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-rir-pointsource_noises-dev-nonzeros.json,
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-rir-pointsource_noises-test-nonzeros.json,
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-rir-pointsource_noises-train-nonzeros.json,
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-rir-real_rirs-dev-nonzeros.json,
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-rir-real_rirs-test-nonzeros.json,
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-rir-real_rirs-train-nonzeros.json,
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-rir-simulated_rirs-dev-nonzeros.json,
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-rir-simulated_rirs-test-nonzeros.json,
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-rir-simulated_rirs-train-nonzeros.json
    ]
    noise_manifest_paths: [
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-musan-music-dev-nonzeros.json,
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-musan-music-test-nonzeros.json,
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-musan-music-train-nonzeros.json,
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-musan-noise-dev-nonzeros.json,
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-musan-noise-test-nonzeros.json,
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-musan-noise-train-nonzeros.json,
    ]
    bg_noise_manifest_paths: [
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-musan-music-dev-nonzeros.json,
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-musan-music-test-nonzeros.json,
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-musan-music-train-nonzeros.json,
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-musan-noise-dev-nonzeros.json,
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-musan-noise-test-nonzeros.json,
        /home/tsargsyan/davit/voxsrc22/voxsrc22-manifests/sr-musan-noise-train-nonzeros.json,
    ]
    rir_prob: 0.5
    min_snr_db: 5
    max_snr_db: 50
    max_additions: 5
    max_duration: 2.0
    bg_min_snr_db: 10
    bg_max_snr_db: 50
    shift_impulse: False
    apply_noise_rir: False

    

noise:
  do_augment: False
  p: 0.15
  params:
      manifest_path: []
      min_snr_db: -8
      max_snr_db: 20
      max_gain_db: 300
      orig_sr: 16000