impulse:
  do_augment: True
  p: 0.1
  params:
    manifest_path: [
      /data/mlsr-data/RIRS_NOISES/rir-proccesed/rir-pointsource_noises.json,
      /data/mlsr-data/RIRS_NOISES/rir-proccesed/rir-simulated_rirs.json,
      /data/mlsr-data/RIRS_NOISES/rir-proccesed/rir-real_rirs_isotropic_noises.json
    ]
    shift_impulse: False

rir:
  do_augment: True
  p: 0.1
  params:
    rir_manifest_path: [
      /data/mlsr-data/RIRS_NOISES/rir-proccesed/rir-pointsource_noises.json,
      /data/mlsr-data/RIRS_NOISES/rir-proccesed/rir-simulated_rirs.json,
      /data/mlsr-data/RIRS_NOISES/rir-proccesed/rir-real_rirs_isotropic_noises.json
    ]
    noise_manifest_paths: [
        /data/mlsr-data/musan/musan-proccesed/musan-music.json,
        /data/mlsr-data/musan/musan-proccesed/musan-noise.json,
    ]
    bg_noise_manifest_paths: [
        /data/mlsr-data/musan/musan-proccesed/musan-music.json,
        /data/mlsr-data/musan/musan-proccesed/musan-noise.json,
    ]
    rir_prob: 0.5
    min_snr_db: 5
    max_snr_db: 50
    max_additions: 5
    max_duration: 2.0
    bg_min_snr_db: 10
    bg_max_snr_db: 50
    shift_impulse: False
    apply_noise_rir: False

crop:
  # Mandatory for speaker recognition task
  do_augment: True
  p: 1.0
  params:
    min_dur: 1
    max_dur: 4

noise:
  do_augment: True
  p: 0.1
  params:
      manifest_path: [
        /data/mlsr-data/musan/musan-proccesed/musan-music.json,
        /data/mlsr-data/musan/musan-proccesed/musan-noise.json,
      ]
      min_snr_db: 0
      max_snr_db: 20
      max_gain_db: 300
      orig_sr: 16000

speed:
  do_augment: True
  p: 0.01
  params:
    sr: 16000
    resample_type: 'soxr_hq'
    min_speed_rate: 0.9
    max_speed_rate: 1.1
    num_rates: 5

codec:
  do_augment: True
  p: 0.01
  params: {}

