ModelCheckpoint:
  do_callback: True
  params:
      monitor: "val_eer"
      filename: "{epoch:002d}-{val_eer:.4f}"
      save_top_k: 4
      verbose: True
      save_last: True
      mode: "min"

LearningRateMonitor:
  do_callback: True
  params:
    logging_interval: 'step'

StochasticWeightAveraging:
  do_callback: False
  params:
      swa_epoch_start: 31