sample_rate: &sample_rate 16000
experiment: &experiment "./dann-log" 

audio_augmentations: "configs/augment.yaml"
spec_augmentations: "configs/spec_augment.yaml"
callbacks: "configs/callbacks.yaml"
explicit_checkpoint_path: null

dann_params:
  gamma: 10
  epoch: &epoch 50
  lr: &lr 0.02
  alpha: 10
  beta: 0.2
  wd: &wd 0.0001

data:
  root_dir: '/data/mlsr-data/cv-corpus-wav'
  params:
    n_views: 4
    train_bs: 64
    eval_bs: 16
    num_workers: 60

# loss:
#   type: "aam"
#   params:
#     scale: 30.0
#     margin: 0.2

loss:
  type: "ge2e"
  params:
    init_w: 10.0
    init_b: -5.0

# loss:
#   type: "angular_proto"
#   params:
#     init_w: 10.0
#     init_b: -5.0

optimizer:
    type: 'sgd'
    params:
        lr: *lr
        momentum: 0.9
        weight_decay: *wd
        nesterov: True

model:
  cfg_path: "configs/model_configs/titanet_medium.yaml"
  featurizer_type: "titanet_medium"
  
  #classifier:
    #classifier_type: "linear"
    #params:
      #angular: True
  
  discriminator:
    discriminator_type: "linear"
    params:
      angular: False
    

preprocessor:
  type: "mel"
  params:
    sample_rate: *sample_rate
    normalize: "per_feature"
    window_size: 0.025
    window_stride: 0.01
    window: "hann"
    features: 80
    n_fft: 512
    frame_splicing: 1
    dither: 0.00001
    pad_to: 16
    pad_value: 0.0

trainer:
    devices: [0, 1]
    max_epochs: *epoch
    strategy: 'ddp'
    accelerator: 'gpu'
    num_nodes: 1
    sync_batchnorm: True
    precision: 16
    val_check_interval: 0.33
