sample_rate: &sample_rate 16000
experiment: &experiment "./classification-log" 

audio_augmentations: "configs/augment.yaml"
spec_augmentations: "configs/spec_augment.yaml"
callbacks: "configs/callbacks.yaml"
explicit_checkpoint_path: null

loss:
  type: "aam"
  params:
    scale: 30
    margin: 0.2

optimizer:
    type: 'sgd'
    params:
        lr: 0.08
        weight_decay: 0.0001
    sched:
         type: 'CosineAnnealing'
         params:
            warmup_ratio: 0.4
            min_lr: 0.005
            max_steps: 500000

model:
  featurizer_type: "titanet_medium"
  classifier_type: "linear"
  params:
    cfg_path: "configs/model_configs/titanet_medium.yaml"
    num_classes: 20000
    angular: True

preprocessor:
  type: "mel"
  params:
    sample_rate: *sample_rate
    normalize: "per_feature"
    window_size: 0.025
    window_stride: 0.01
    window: "hann"
    features: 80
    n_fft: 512
    frame_splicing: 1
    dither: 0.00001
    pad_to: 16
    pad_value: 0.0

trainer:
    devices: [0]
    max_epochs: 250
    strategy: 'ddp'
    accelerator: 'gpu'
    num_nodes: 1
    sync_batchnorm: True
    precision: 32
    val_check_interval: 0.5

